In [3]:
import pandas as pd
import numpy as np

In [8]:
#REad the data
#read the data type
#first and last rows of data
#business understanding of data
#statastical check

In [2]:
#json-javascript object notation
dict1={"Name":["Mohit","Akanksha"],
  "Class":"FSDS Pro"
}

In [3]:
url = "https://api.github.com/repos/pandas-dev/pandas/issues"

In [4]:
pd.read_json(url)

,url,repository_url,labels_url,comments_url,events_url,html_url,id,node_id,number,title,...,closed_at,author_association,active_lock_reason,draft,pull_request,body,reactions,timeline_url,performed_via_github_app,state_reason
0,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/58091,2216730815,PR_kwDOAA0YD85rPMrj,58091,"DOC: Changed ndim to 1, modified doc as sugges...",...,NaT,NONE,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #57088,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
1,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/58090,2216715546,PR_kwDOAA0YD85rPJ1e,58090,CI: Remove deprecated methods from code_checks.sh,...,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] xref #58065 \r\n- [ ] [Tests added and p...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
2,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/58089,2216677095,PR_kwDOAA0YD85rPDMB,58089,DEPR: Series setitem/getitem treating ints as ...,...,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #xxxx (Replace xxxx with the GitH...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
3,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/58088,2216668448,PR_kwDOAA0YD85rPBn7,58088,BUG: Let `melt` name multiple variable columns...,...,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #58033\r\n- [x] [Tests added and ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
4,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/58087,2216590838,PR_kwDOAA0YD85rOzGF,58087,BLD: Build wheels using numpy 2.0rc1,...,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #55519 (Replace xxxx with the Gi...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
5,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/58086,2216550242,I_kwDOAA0YD86EHd9i,58086,BUG: beautifulsoup4 breaks pandas.read_html,...,NaT,CONTRIBUTOR,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
6,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/58085,2216480869,PR_kwDOAA0YD85rOcSY,58085,ENH: Enable fillna(value=None),...,NaT,MEMBER,NaN,1.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #57723 (Replace xxxx with the Git...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
7,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/58084,2216346242,PR_kwDOAA0YD85rOBlK,58084,Use mask to create result_mask that filters na...,...,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #xxxx (Replace xxxx with the GitH...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
8,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/58083,2216118389,PR_kwDOAA0YD85rNTlX,58083,CLN: move raising TypeError for `interpolate` ...,...,NaT,CONTRIBUTOR,NaN,1.0,{'url': 'https://api.github.com/repos/pandas-d...,xref #57820\r\n\r\nmoved raising `TypeError` f...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
9,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/58082,2216062901,PR_kwDOAA0YD85rNIGP,58082,Improve MultiIndex label rename checks,...,NaT,NONE,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #55169 \r\n- [x] [Tests added and...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
10,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/58081,2216037782,PR_kwDOAA0YD85rNC0I,58081,ENH: Implement round dunder methods for Timest...,...,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #58071\r\n- [ ] [Tests added and ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
11,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/58080,2216022704,PR_kwDOAA0YD85rM_o_,58080,Backport PR #58075 on branch 2.2.x (DOC: whats...,...,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,Backport PR #58075: DOC: whatsnew note for #57553,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
12,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/58079,2215997850,PR_kwDOAA0YD85rM6Zi,58079,DOC: Update Categorical/CategoricalDtype metho...,...,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #58064 \r\n- [ ] [Tests added and...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
13,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/58078,2215950924,I_kwDOAA0YD86EFLpM,58078,BUG: Read hdfs:/// is broken since 2.1.0,...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
14,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/58076,2215864273,PR_kwDOAA0YD85rMeMR,58076,DOC: docstring fix for pandas.DataFrame.where ...,...,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] xref #58065 (Replace xxxx with the GitHu...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
15,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/58074,2215748323,PR_kwDOAA0YD85rMEi6,58074,DOC: fixed docstrings for pandas.DatetimeIndex...,...,NaT,NONE,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] [Tests added and passed](https://pandas....,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
16,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/58072,2215498582,PR_kwDOAA0YD85rLODq,58072,Add `strict_na` keyword to the assert_.._equal...,...,NaT,MEMBER,NaN,1.0,{'url': 'https://api.github.com/repos/pandas-d...,Adding a `strict_na=False` option to our asser...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
17,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/58071,2215159792,I_kwDOAA0YD86ECKfw,58071,"BUG: TypeError(""type Timedelta doesn't define ...",...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
18,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/58070,2215042082,I_kwDOAA0YD86EBtwi,58070,ENH: styler.to_excel to support excel notes as...,...,NaT,CONTRIBUTOR,NaN,NaN,NaN,### Feature Type\n\n- [X] Adding new functiona...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
19,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/58069,2215041281,I_kwDOAA0YD86EBtkB,58069,BUG: Linux - Name of the returned series dropp...,...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
20,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/58068,2214815264,I_kwDOAA0YD86EA2Yg,58068,DOC: Enforce Numpy Docstring Validation | pand...,...,NaT,CONTRIBUTOR,NaN,NaN,NaN,[DOC: Enforce Numpy Docstring Validation (Pare...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
21,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/58067,2214811314,I_kwDOAA0YD86EA1ay,58067,DOC: Enforce Numpy Docstring Validation | pand...,...,NaT,CONTRIBUTOR,NaN,NaN,NaN,[DOC: Enforce Numpy Docstring Validation (Pare...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
22,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/58066,2214794201,I_kwDOAA0YD86EAxPZ,58066,DOC: Enforce Numpy Docstring Validation | pand...,...,NaT,CONTRIBUTOR,NaN,NaN,NaN,[DOC: Enforce Numpy Docstring Validation (Pare...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
23,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/58065,2214790285,I_kwDOAA0YD86EAwSN,58065,DOC: Enforce Numpy Docstring Validation | pand...,...,NaT,CONTRIBUTOR,NaN,NaN,NaN,[DOC: Enforce Numpy Docstring Validation (Pare...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
24,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/58064,2214788325,I_kwDOAA0YD86EAvzl,58064,DOC: Enforce Numpy Docstring Validation | pand...,...,NaT,CONTRIBUTOR,NaN,NaN,NaN,[DOC: Enforce Numpy Docstring Validation (Pare...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
25,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/58063,2214763738,I_kwDOAA0YD86EApza,58063,DOC: Enforce Numpy Docstring Validation (Paren...,...,NaT,CONTRIBUTOR,NaN,NaN,NaN,Pandas has a script for validating docstrings:...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
26,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/58062,2214674078,I_kwDOAA0YD86EAT6e,58062,BUG: Categorical columns using the PyArrow bac...,...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
27,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/58061,2214579740,I_kwDOAA0YD86D_84c,58061,QST: somthing weird in using groupby.rolling.a...,...,NaT,NONE,NaN,NaN,NaN,### Research\n\n- [X] I have searched the [[pa...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
28,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/58057,2214305563,PR_kwDOAA0YD85rHLPE,58057,BUG: Allow using numpy in `DataFrame.eval` and...,...,NaT,NONE,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #58041\r\n- [x] [Tests added and ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
29,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/58055,2214262085,I_kwDOAA0YD86D-vVF,58055,BUG: TestTableSchemaRepr::test_publishes raise...,...,NaT,MEMBER,NaN,NaN,NaN,```python\r\nTestTableSchemaRepr::test_publish...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN

In [5]:
import requests
data=requests.get(url)

In [6]:
data

In [7]:
df=data.json()

In [8]:
df

[{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58091',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58091/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58091/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58091/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/58091',
  'id': 2216730815,
  'node_id': 'PR_kwDOAA0YD85rPMrj',
  'number': 58091,
  'title': 'DOC: Changed ndim to 1, modified doc as suggested. #57088',
  'user': {'login': 'lamprinikourou',
   'id': 127689412,
   'node_id': 'U_kgDOB5xixA',
   'avatar_url': 'https://avatars.githubusercontent.com/u/127689412?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/lamprinikourou',
   'html_url': 'https://github.com/lamprinikourou',
   'followers_url': 'https://api.github.com/users/lamprinikourou/followers',
   'following_url': 'https://api.github.com/users/lamprinikourou/following{/other_user}',
   'gists_url': 'https://api.github.com/users/lamprinikourou/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/lamprinikourou/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/lamprinikourou/subscriptions',
   'organizations_url': 'https://api.github.com/users/lamprinikourou/orgs',
   'repos_url': 'https://api.github.com/users/lamprinikourou/repos',
   'events_url': 'https://api.github.com/users/lamprinikourou/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/lamprinikourou/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2024-03-31T01:28:35Z',
  'updated_at': '2024-03-31T02:06:09Z',
  'closed_at': None,
  'author_association': 'NONE',
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/58091',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/58091',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/58091.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/58091.patch',
   'merged_at': None},
  'body': '- [ ] closes #57088 ',
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58091/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58091/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58090',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58090/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58090/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58090/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/58090',
  'id': 2216715546,
  'node_id': 'PR_kwDOAA0YD85rPJ1e',
  'number': 58090,
  'title': 'CI: Remove deprecated methods from code_checks.sh',
  'user': {'login': 'Aloqeely',
   'id': 52792999,
   'node_id': 'MDQ6VXNlcjUyNzkyOTk5',
   'avatar_url': 'https://avatars.githubusercontent.com/u/52792999?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/Aloqeely',
   'html_url': 'https://github.com/Aloqeely',
   'followers_url': 'https://api.github.com/users/Aloqeely/followers',
   'following_url': 'https://api.github.com/users/Aloqeely/following{/other_user}',
   'gists_url': 'https://api.github.com/users/Aloqeely/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/Aloqeely/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/Aloqeely/subscriptions',
   'organizations_url': 'https://api.github.com/users/Aloqeely/orgs',
   'repos_url': 'https://api.github.com/users/Aloqeely/repos',
   'events_url': 'https://api.github.com/users/Aloqeely/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/Aloqeely/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2024-03-31T00:22:21Z',
  'updated_at': '2024-03-31T00:22:21Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/58090',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/58090',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/58090.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/58090.patch',
   'merged_at': None},
  'body': '- [ ] xref #58065 \r\n- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\r\n- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.\r\n- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\r\n',
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58090/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58090/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58089',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58089/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58089/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58089/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/58089',
  'id': 2216677095,
  'node_id': 'PR_kwDOAA0YD85rPDMB',
  'number': 58089,
  'title': 'DEPR: Series setitem/getitem treating ints as positional',
  'user': {'login': 'jbrockmendel',
   'id': 8078968,
   'node_id': 'MDQ6VXNlcjgwNzg5Njg=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/jbrockmendel',
   'html_url': 'https://github.com/jbrockmendel',
   'followers_url': 'https://api.github.com/users/jbrockmendel/followers',
   'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}',
   'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions',
   'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs',
   'repos_url': 'https://api.github.com/users/jbrockmendel/repos',
   'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2024-03-30T21:53:17Z',
  'updated_at': '2024-03-30T21:53:17Z',
  'closed_at': None,
  'author_association': 'MEMBER',
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/58089',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/58089',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/58089.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/58089.patch',
   'merged_at': None},
  'body': '- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)\r\n- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\r\n- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.\r\n- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\r\n',
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58089/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58089/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58088',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58088/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58088/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58088/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/58088',
  'id': 2216668448,
  'node_id': 'PR_kwDOAA0YD85rPBn7',
  'number': 58088,
  'title': 'BUG: Let `melt` name multiple variable columns for labels from a `MultiIndex`',
  'user': {'login': 'rob-sil',
   'id': 124158982,
   'node_id': 'U_kgDOB2aEBg',
   'avatar_url': 'https://avatars.githubusercontent.com/u/124158982?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/rob-sil',
   'html_url': 'https://github.com/rob-sil',
   'followers_url': 'https://api.github.com/users/rob-sil/followers',
   'following_url': 'https://api.github.com/users/rob-sil/following{/other_user}',
   'gists_url': 'https://api.github.com/users/rob-sil/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/rob-sil/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/rob-sil/subscriptions',
   'organizations_url': 'https://api.github.com/users/rob-sil/orgs',
   'repos_url': 'https://api.github.com/users/rob-sil/repos',
   'events_url': 'https://api.github.com/users/rob-sil/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/rob-sil/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2024-03-30T21:20:09Z',
  'updated_at': '2024-03-30T23:09:43Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/58088',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/58088',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/58088.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/58088.patch',
   'merged_at': None},
  'body': '- [x] closes #58033\r\n- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\r\n- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.\r\n- [x] Added an entry in the latest `doc/source/whatsnew/v2.2.2.rst` file if fixing a bug or adding a new feature.\r\n\r\nIf there are fewer names provided in `var_name` than levels in the columns `MultiIndex`, then `melt` will just take the first several. I personally find this a bit strange, but it keeps with the previous behavior of `melt` with a `MultiIndex` where you could pass it a single name and it would only use one level of the `MultiIndex`.',
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58088/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58088/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58087',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58087/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58087/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58087/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/58087',
  'id': 2216590838,
  'node_id': 'PR_kwDOAA0YD85rOzGF',
  'number': 58087,
  'title': 'BLD: Build wheels using numpy 2.0rc1',
  'user': {'login': 'lithomas1',
   'id': 47963215,
   'node_id': 'MDQ6VXNlcjQ3OTYzMjE1',
   'avatar_url': 'https://avatars.githubusercontent.com/u/47963215?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/lithomas1',
   'html_url': 'https://github.com/lithomas1',
   'followers_url': 'https://api.github.com/users/lithomas1/followers',
   'following_url': 'https://api.github.com/users/lithomas1/following{/other_user}',
   'gists_url': 'https://api.github.com/users/lithomas1/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/lithomas1/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/lithomas1/subscriptions',
   'organizations_url': 'https://api.github.com/users/lithomas1/orgs',
   'repos_url': 'https://api.github.com/users/lithomas1/repos',
   'events_url': 'https://api.github.com/users/lithomas1/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/lithomas1/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 129350,
    'node_id': 'MDU6TGFiZWwxMjkzNTA=',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Build',
    'name': 'Build',
    'color': '75507B',
    'default': False,
    'description': 'Library building on various platforms'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': {'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/117',
   'html_url': 'https://github.com/pandas-dev/pandas/milestone/117',
   'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/117/labels',
   'id': 10539704,
   'node_id': 'MI_kwDOAA0YD84AoNK4',
   'number': 117,
   'title': '2.2.2',
   'description': 'on-merge: backport to 2.2.x',
   'creator': {'login': 'lithomas1',
    'id': 47963215,
    'node_id': 'MDQ6VXNlcjQ3OTYzMjE1',
    'avatar_url': 'https://avatars.githubusercontent.com/u/47963215?v=4',
    'gravatar_id': '',
    'url': 'https://api.github.com/users/lithomas1',
    'html_url': 'https://github.com/lithomas1',
    'followers_url': 'https://api.github.com/users/lithomas1/followers',
    'following_url': 'https://api.github.com/users/lithomas1/following{/other_user}',
    'gists_url': 'https://api.github.com/users/lithomas1/gists{/gist_id}',
    'starred_url': 'https://api.github.com/users/lithomas1/starred{/owner}{/repo}',
    'subscriptions_url': 'https://api.github.com/users/lithomas1/subscriptions',
    'organizations_url': 'https://api.github.com/users/lithomas1/orgs',
    'repos_url': 'https://api.github.com/users/lithomas1/repos',
    'events_url': 'https://api.github.com/users/lithomas1/events{/privacy}',
    'received_events_url': 'https://api.github.com/users/lithomas1/received_events',
    'type': 'User',
    'site_admin': False},
   'open_issues': 44,
   'closed_issues': 54,
   'state': 'open',
   'created_at': '2024-02-10T23:53:00Z',
   'updated_at': '2024-03-30T17:21:12Z',
   'due_on': None,
   'closed_at': None},
  'comments': 0,
  'created_at': '2024-03-30T17:21:12Z',
  'updated_at': '2024-03-30T19:56:18Z',
  'closed_at': None,
  'author_association': 'MEMBER',
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/58087',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/58087',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/58087.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/58087.patch',
   'merged_at': None},
  'body': '- [ ] closes #55519  (Replace xxxx with the GitHub issue number)\r\n- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\r\n- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.\r\n- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\r\n',
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58087/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58087/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58086',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58086/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58086/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58086/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/58086',
  'id': 2216550242,
  'node_id': 'I_kwDOAA0YD86EHd9i',
  'number': 58086,
  'title': 'BUG: beautifulsoup4 breaks pandas.read_html',
  'user': {'login': 'neutrinoceros',
   'id': 14075922,
   'node_id': 'MDQ6VXNlcjE0MDc1OTIy',
   'avatar_url': 'https://avatars.githubusercontent.com/u/14075922?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/neutrinoceros',
   'html_url': 'https://github.com/neutrinoceros',
   'followers_url': 'https://api.github.com/users/neutrinoceros/followers',
   'following_url': 'https://api.github.com/users/neutrinoceros/following{/other_user}',
   'gists_url': 'https://api.github.com/users/neutrinoceros/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/neutrinoceros/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/neutrinoceros/subscriptions',
   'organizations_url': 'https://api.github.com/users/neutrinoceros/orgs',
   'repos_url': 'https://api.github.com/users/neutrinoceros/repos',
   'events_url': 'https://api.github.com/users/neutrinoceros/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/neutrinoceros/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 76811,
    'node_id': 'MDU6TGFiZWw3NjgxMQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',
    'name': 'Bug',
    'color': 'e10c02',
    'default': False,

In [9]:
len(df)

30

In [10]:
for i in range(len(df)):
    print(df[i])

{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58091', 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58091/labels{/name}', 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58091/comments', 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58091/events', 'html_url': 'https://github.com/pandas-dev/pandas/pull/58091', 'id': 2216730815, 'node_id': 'PR_kwDOAA0YD85rPMrj', 'number': 58091, 'title': 'DOC: Changed ndim to 1, modified doc as suggested. #57088', 'user': {'login': 'lamprinikourou', 'id': 127689412, 'node_id': 'U_kgDOB5xixA', 'avatar_url': 'https://avatars.githubusercontent.com/u/127689412?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lamprinikourou', 'html_url': 'https://github.com/lamprinikourou', 'followers_url': 'https://api.github.com/users/lamprinikourou/followers', 'following_url': 'https://api.github.com/users/lamprinikourou/following{/other_user}', 'gists_url': 'https://api.github.com/users/lamprinikourou/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lamprinikourou/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lamprinikourou/subscriptions', 'organizations_url': 'https://api.github.com/users/lamprinikourou/orgs', 'repos_url': 'https://api.github.com/users/lamprinikourou/repos', 'events_url': 'https://api.github.com/users/lamprinikourou/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lamprinikourou/received_events', 'type': 'User', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 0, 'created_at': '2024-03-31T01:28:35Z', 'updated_at': '2024-03-31T02:06:09Z', 'closed_at': None, 'author_association': 'NONE', 'active_lock_reason': None, 'draft': False, 'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/58091', 'html_url': 'https://github.com/pandas-dev/pandas/pull/58091', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/58091.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/58091.patch', 'merged_at': None}, 'body': '- [ ] closes #57088 ', 'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58091/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58091/timeline', 'performed_via_github_app': None, 'state_reason': None}
{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58090', 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58090/labels{/name}', 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58090/comments', 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58090/events', 'html_url': 'https://github.com/pandas-dev/pandas/pull/58090', 'id': 2216715546, 'node_id': 'PR_kwDOAA0YD85rPJ1e', 'number': 58090, 'title': 'CI: Remove deprecated methods from code_checks.sh', 'user': {'login': 'Aloqeely', 'id': 52792999, 'node_id': 'MDQ6VXNlcjUyNzkyOTk5', 'avatar_url': 'https://avatars.githubusercontent.com/u/52792999?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Aloqeely', 'html_url': 'https://github.com/Aloqeely', 'followers_url': 'https://api.github.com/users/Aloqeely/followers', 'following_url': 'https://api.github.com/users/Aloqeely/following{/other_user}', 'gists_url': 'https://api.github.com/users/Aloqeely/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Aloqeely/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Aloqeely/subscriptions', 'organizations_url': 'https://api.github.com/users/Aloqeely/orgs', 'repos_url': 'https://api.github.com/users/Aloqeely/repos', 'events_url': 'https://api.github.com/users/Aloqeely/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Aloqeely/received_events', 'type': 'User', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 0, 'created_at': '2024-03-31T00:22:21Z', 'updated_at': '2024-03-31T00:22:21Z', 'closed_at': None, 'author_association': 'CONTRIBUTOR', 'active_lock_reason': None, 'draft': False, 'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/58090', 'html_url': 'https://github.com/pandas-dev/pandas/pull/58090', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/58090.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/58090.patch', 'merged_at': None}, 'body': '- [ ] xref #58065 \r\n- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\r\n- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.\r\n- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\r\n', 'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58090/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58090/timeline', 'performed_via_github_app': None, 'state_reason': None}
{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58089', 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58089/labels{/name}', 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58089/comments', 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58089/events', 'html_url': 'https://github.com/pandas-dev/pandas/pull/58089', 'id': 2216677095, 'node_id': 'PR_kwDOAA0YD85rPDMB', 'number': 58089, 'title': 'DEPR: Series setitem/getitem treating ints as positional', 'user': {'login': 'jbrockmendel', 'id': 8078968, 'node_id': 'MDQ6VXNlcjgwNzg5Njg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jbrockmendel', 'html_url': 'https://github.com/jbrockmendel', 'followers_url': 'https://api.github.com/users/jbrockmendel/followers', 'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}', 'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions', 'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs', 'repos_url': 'https://api.github.com/users/jbrockmendel/repos', 'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events', 'type': 'User', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 0, 'created_at': '2024-03-30T21:53:17Z', 'updated_at': '2024-03-30T21:53:17Z', 'closed_at': None, 'author_association': 'MEMBER', 'active_lock_reason': None, 'draft': False, 'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/58089', 'html_url': 'https://github.com/pandas-dev/pandas/pull/58089', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/58089.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/58089.patch', 'merged_at': None}, 'body': '- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)\r\n- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\r\n- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.\r\n- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\r\n', 'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58089/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58089/timeline', 'performed_via_github_app': None, 'state_reason': None}
{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58088', 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58088/labels{/name}', 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58088/comments', 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58088/events', 'html_url': 'https://github.com/pandas-dev/pandas/pull/58088', 'id': 2216668448, 'node_id': 'PR_kwDOAA0YD85rPBn7', 'number': 58088, 'title': 'BUG: Let `melt` name multiple variable columns for labels from a `MultiIndex`', 'user': {'login': 'rob-sil', 'id': 124158982, 'node_id': 'U_kgDOB2aEBg', 'avatar_url': 'https://avatars.githubusercontent.com/u/124158982?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/rob-sil', 'html_url': 'https://github.com/rob-sil', 'followers_url': 'https://api.github.com/users/rob-sil/followers', 'following_url': 'https://api.github.com/users/rob-sil/following{/other_user}', 'gists_url': 'https://api.github.com/users/rob-sil/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/rob-sil/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/rob-sil/subscriptions', 'organizations_url': 'https://api.github.com/users/rob-sil/orgs', 'repos_url': 'https://api.github.com/users/rob-sil/repos', 'events_url': 'https://api.github.com/users/rob-sil/events{/privacy}', 'received_events_url': 'https://api.github.com/users/rob-sil/received_events', 'type': 'User', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 0, 'created_at': '2024-03-30T21:20:09Z', 'updated_at': '2024-03-30T23:09:43Z', 'closed_at': None, 'author_association': 'CONTRIBUTOR', 'active_lock_reason': None, 'draft': False, 'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/58088', 'html_url': 'https://github.com/pandas-dev/pandas/pull/58088', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/58088.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/58088.patch', 'merged_at': None}, 'body': '- [x] closes #58033\r\n- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\r\n- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.\r\n- [x] Added an entry in the latest `doc/source/whatsnew/v2.2.2.rst` file if fixing a bug or adding a new feature.\r\n\r\nIf there are fewer names provided in `var_name` than levels in the columns `MultiIndex`, then `melt` will just take the first several. I personally find this a bit strange, but it keeps with the previous behavior of `melt` with a `MultiIndex` where you could pass it a single name and it would only use one level of the `MultiIndex`.', 'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58088/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58088/timeline', 'performed_via_github_app': None, 'state_reason': None}
{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58087', 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58087/labels{/name}', 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58087/comments', 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58087/events', 'html_url': 'https://github.com/pandas-dev/pandas/pull/58087', 'id': 2216590838, 'node_id': 'PR_kwDOAA0YD85rOzGF', 'number': 58087, 'title': 'BLD: Build wheels using numpy 2.0rc1', 'user': {'login': 'lithomas1', 'id': 47963215, 'node_id': 'MDQ6VXNlcjQ3OTYzMjE1', 'avatar_url': 'https://avatars.githubusercontent.com/u/47963215?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lithomas1', 'html_url': 'https://github.com/lithomas1', 'followers_url': 'https://api.github.com/users/lithomas1/followers', 'following_url': 'https://api.github.com/users/lithomas1/following{/other_user}', 'gists_url': 'https://api.github.com/users/lithomas1/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lithomas1/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lithomas1/subscriptions', 'organizations_url': 'https://api.github.com/users/lithomas1/orgs', 'repos_url': 'https://api.github.com/users/lithomas1/repos', 'events_url': 'https://api.github.com/users/lithomas1/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lithomas1/received_events', 'type': 'User', 'site_admin': False}, 'labels': [{'id': 129350, 'node_id': 'MDU6TGFiZWwxMjkzNTA=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Build', 'name': 'Build', 'color': '75507B', 'default': False, 'description': 'Library building on various platforms'}], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': {'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/117', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/117', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/117/labels', 'id': 10539704, 'node_id': 'MI_kwDOAA0YD84AoNK4', 'number': 117, 'title': '2.2.2', 'description': 'on-merge: backport to 2.2.x', 'creator': {'login': 'lithomas1', 'id': 47963215, 'node_id': 'MDQ6VXNlcjQ3OTYzMjE1', 'avatar_url': 'https://avatars.githubusercontent.com/u/47963215?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lithomas1', 'html_url': 'https://github.com/lithomas1', 'followers_url': 'https://api.github.com/users/lithomas1/followers', 'following_url': 'https://api.github.com/users/lithomas1/following{/other_user}', 'gists_url': 'https://api.github.com/users/lithomas1/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lithomas1/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lithomas1/subscriptions', 'organizations_url': 'https://api.github.com/users/lithomas1/orgs', 'repos_url': 'https://api.github.com/users/lithomas1/repos', 'events_url': 'https://api.github.com/users/lithomas1/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lithomas1/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 44, 'closed_issues': 54, 'state': 'open', 'created_at': '2024-02-10T23:53:00Z', 'updated_at': '2024-03-30T17:21:12Z', 'due_on': None, 'closed_at': None}, 'comments': 0, 'created_at': '2024-03-30T17:21:12Z', 'updated_at': '2024-03-30T19:56:18Z', 'closed_at': None, 'author_association': 'MEMBER', 'active_lock_reason': None, 'draft': False, 'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/58087', 'html_url': 'https://github.com/pandas-dev/pandas/pull/58087', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/58087.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/58087.patch', 'merged_at': None}, 'body': '- [ ] closes #55519  (Replace xxxx with the GitHub issue number)\r\n- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\r\n- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.\r\n- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\r\n', 'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58087/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58087/timeline', 'performed_via_github_app': None, 'state_reason': None}

In [11]:
for i in range(len(df)):
    print(df[i]['user'])

{'login': 'lamprinikourou', 'id': 127689412, 'node_id': 'U_kgDOB5xixA', 'avatar_url': 'https://avatars.githubusercontent.com/u/127689412?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lamprinikourou', 'html_url': 'https://github.com/lamprinikourou', 'followers_url': 'https://api.github.com/users/lamprinikourou/followers', 'following_url': 'https://api.github.com/users/lamprinikourou/following{/other_user}', 'gists_url': 'https://api.github.com/users/lamprinikourou/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lamprinikourou/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lamprinikourou/subscriptions', 'organizations_url': 'https://api.github.com/users/lamprinikourou/orgs', 'repos_url': 'https://api.github.com/users/lamprinikourou/repos', 'events_url': 'https://api.github.com/users/lamprinikourou/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lamprinikourou/received_events', 'type': 'User', 'site_admin': False}
{'login': 'Aloqeely', 'id': 52792999, 'node_id': 'MDQ6VXNlcjUyNzkyOTk5', 'avatar_url': 'https://avatars.githubusercontent.com/u/52792999?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Aloqeely', 'html_url': 'https://github.com/Aloqeely', 'followers_url': 'https://api.github.com/users/Aloqeely/followers', 'following_url': 'https://api.github.com/users/Aloqeely/following{/other_user}', 'gists_url': 'https://api.github.com/users/Aloqeely/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Aloqeely/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Aloqeely/subscriptions', 'organizations_url': 'https://api.github.com/users/Aloqeely/orgs', 'repos_url': 'https://api.github.com/users/Aloqeely/repos', 'events_url': 'https://api.github.com/users/Aloqeely/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Aloqeely/received_events', 'type': 'User', 'site_admin': False}
{'login': 'jbrockmendel', 'id': 8078968, 'node_id': 'MDQ6VXNlcjgwNzg5Njg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jbrockmendel', 'html_url': 'https://github.com/jbrockmendel', 'followers_url': 'https://api.github.com/users/jbrockmendel/followers', 'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}', 'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions', 'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs', 'repos_url': 'https://api.github.com/users/jbrockmendel/repos', 'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events', 'type': 'User', 'site_admin': False}
{'login': 'rob-sil', 'id': 124158982, 'node_id': 'U_kgDOB2aEBg', 'avatar_url': 'https://avatars.githubusercontent.com/u/124158982?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/rob-sil', 'html_url': 'https://github.com/rob-sil', 'followers_url': 'https://api.github.com/users/rob-sil/followers', 'following_url': 'https://api.github.com/users/rob-sil/following{/other_user}', 'gists_url': 'https://api.github.com/users/rob-sil/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/rob-sil/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/rob-sil/subscriptions', 'organizations_url': 'https://api.github.com/users/rob-sil/orgs', 'repos_url': 'https://api.github.com/users/rob-sil/repos', 'events_url': 'https://api.github.com/users/rob-sil/events{/privacy}', 'received_events_url': 'https://api.github.com/users/rob-sil/received_events', 'type': 'User', 'site_admin': False}
{'login': 'lithomas1', 'id': 47963215, 'node_id': 'MDQ6VXNlcjQ3OTYzMjE1', 'avatar_url': 'https://avatars.githubusercontent.com/u/47963215?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lithomas1', 'html_url': 'https://github.com/lithomas1', 'followers_url': 'https://api.github.com/users/lithomas1/followers', 'following_url': 'https://api.github.com/users/lithomas1/following{/other_user}', 'gists_url': 'https://api.github.com/users/lithomas1/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lithomas1/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lithomas1/subscriptions', 'organizations_url': 'https://api.github.com/users/lithomas1/orgs', 'repos_url': 'https://api.github.com/users/lithomas1/repos', 'events_url': 'https://api.github.com/users/lithomas1/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lithomas1/received_events', 'type': 'User', 'site_admin': False}
{'login': 'neutrinoceros', 'id': 14075922, 'node_id': 'MDQ6VXNlcjE0MDc1OTIy', 'avatar_url': 'https://avatars.githubusercontent.com/u/14075922?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/neutrinoceros', 'html_url': 'https://github.com/neutrinoceros', 'followers_url': 'https://api.github.com/users/neutrinoceros/followers', 'following_url': 'https://api.github.com/users/neutrinoceros/following{/other_user}', 'gists_url': 'https://api.github.com/users/neutrinoceros/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/neutrinoceros/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/neutrinoceros/subscriptions', 'organizations_url': 'https://api.github.com/users/neutrinoceros/orgs', 'repos_url': 'https://api.github.com/users/neutrinoceros/repos', 'events_url': 'https://api.github.com/users/neutrinoceros/events{/privacy}', 'received_events_url': 'https://api.github.com/users/neutrinoceros/received_events', 'type': 'User', 'site_admin': False}
{'login': 'rhshadrach', 'id': 45562402, 'node_id': 'MDQ6VXNlcjQ1NTYyNDAy', 'avatar_url': 'https://avatars.githubusercontent.com/u/45562402?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/rhshadrach', 'html_url': 'https://github.com/rhshadrach', 'followers_url': 'https://api.github.com/users/rhshadrach/followers', 'following_url': 'https://api.github.com/users/rhshadrach/following{/other_user}', 'gists_url': 'https://api.github.com/users/rhshadrach/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/rhshadrach/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/rhshadrach/subscriptions', 'organizations_url': 'https://api.github.com/users/rhshadrach/orgs', 'repos_url': 'https://api.github.com/users/rhshadrach/repos', 'events_url': 'https://api.github.com/users/rhshadrach/events{/privacy}', 'received_events_url': 'https://api.github.com/users/rhshadrach/received_events', 'type': 'User', 'site_admin': False}
{'login': 'undermyumbrella1', 'id': 120079323, 'node_id': 'U_kgDOByhD2w', 'avatar_url': 'https://avatars.githubusercontent.com/u/120079323?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/undermyumbrella1', 'html_url': 'https://github.com/undermyumbrella1', 'followers_url': 'https://api.github.com/users/undermyumbrella1/followers', 'following_url': 'https://api.github.com/users/undermyumbrella1/following{/other_user}', 'gists_url': 'https://api.github.com/users/undermyumbrella1/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/undermyumbrella1/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/undermyumbrella1/subscriptions', 'organizations_url': 'https://api.github.com/users/undermyumbrella1/orgs', 'repos_url': 'https://api.github.com/users/undermyumbrella1/repos', 'events_url': 'https://api.github.com/users/undermyumbrella1/events{/privacy}', 'received_events_url': 'https://api.github.com/users/undermyumbrella1/received_events', 'type': 'User', 'site_admin': False}
{'login': 'natmokval', 'id': 91160475, 'node_id': 'MDQ6VXNlcjkxMTYwNDc1', 'avatar_url': 'https://avatars.githubusercontent.com/u/91160475?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/natmokval', 'html_url': 'https://github.com/natmokval', 'followers_url': 'https://api.github.com/users/natmokval/followers', 'following_url': 'https://api.github.com/users/natmokval/following{/other_user}', 'gists_url': 'https://api.github.com/users/natmokval/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/natmokval/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/natmokval/subscriptions', 'organizations_url': 'https://api.github.com/users/natmokval/orgs', 'repos_url': 'https://api.github.com/users/natmokval/repos', 'events_url': 'https://api.github.com/users/natmokval/events{/privacy}', 'received_events_url': 'https://api.github.com/users/natmokval/received_events', 'type': 'User', 'site_admin': False}
{'login': 'TabLand', 'id': 2546543, 'node_id': 'MDQ6VXNlcjI1NDY1NDM=', 'avatar_url': 'https://avatars.githubusercontent.com/u/2546543?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/TabLand', 'html_url': 'https://github.com/TabLand', 'followers_url': 'https://api.github.com/users/TabLand/followers', 'following_url': 'https://api.github.com/users/TabLand/following{/other_user}', 'gists_url': 'https://api.github.com/users/TabLand/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/TabLand/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/TabLand/subscriptions', 'organizations_url': 'https://api.github.com/users/TabLand/orgs', 'repos_url': 'https://api.github.com/users/TabLand/repos', 'events_url': 'https://api.github.com/users/TabLand/events{/privacy}', 'received_events_url': 'https://api.github.com/users/TabLand/received_events', 'type': 'User', 'site_admin': False}
{'login': 'Aloqeely', 'id': 52792999, 'node_id': 'MDQ6VXNlcjUyNzkyOTk5', 'avatar_url': 'https://avatars.githubusercontent.com/u/52792999?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Aloqeely', 'html_url': 'https://github.com/Aloqeely', 'followers_url': 'https://api.github.com/users/Aloqeely/followers', 'following_url': 'https://api.github.com/users/Aloqeely/following{/other_user}', 'gists_url': 'https://api.github.com/users/Aloqeely/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Aloqeely/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Aloqeely/subscriptions', 'organizations_url': 'https://api.github.com/users/Aloqeely/orgs', 'repos_url': 'https://api.github.com/users/Aloqeely/repos', 'events_url': 'https://api.github.com/users/Aloqeely/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Aloqeely/received_events', 'type': 'User', 'site_admin': False}
{'login': 'meeseeksmachine', 'id': 39504233, 'node_id': 'MDQ6VXNlcjM5NTA0MjMz', 'avatar_url': 'https://avatars.githubusercontent.com/u/39504233?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/meeseeksmachine', 'html_url': 'https://github.com/meeseeksmachine', 'followers_url': 'https://api.github.com/users/meeseeksmachine/followers', 'following_url': 'https://api.github.com/users/meeseeksmachine/following{/other_user}', 'gists_url': 'https://api.github.com/users/meeseeksmachine/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/meeseeksmachine/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/meeseeksmachine/subscriptions', 'organizations_url': 'https://api.github.com/users/meeseeksmachine/orgs', 'repos_url': 'https://api.github.com/users/meeseeksmachine/repos', 'events_url': 'https://api.github.com/users/meeseeksmachine/events{/privacy}', 'received_events_url': 'https://api.github.com/users/meeseeksmachine/received_events', 'type': 'User', 'site_admin': False}
{'login': 'Aloqeely', 'id': 52792999, 'node_id': 'MDQ6VXNlcjUyNzkyOTk5', 'avatar_url': 'https://avatars.githubusercontent.com/u/52792999?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Aloqeely', 'html_url': 'https://github.com/Aloqeely', 'followers_url': 'https://api.github.com/users/Aloqeely/followers', 'following_url': 'https://api.github.com/users/Aloqeely/following{/other_user}', 'gists_url': 'https://api.github.com/users/Aloqeely/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Aloqeely/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Aloqeely/subscriptions', 'organizations_url': 'https://api.github.com/users/Aloqeely/orgs', 'repos_url': 'https://api.github.com/users/Aloqeely/repos', 'events_url': 'https://api.github.com/users/Aloqeely/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Aloqeely/received_events', 'type': 'User', 'site_admin': False}
{'login': 'yli7-bloomberg', 'id': 65625348, 'node_id': 'MDQ6VXNlcjY1NjI1MzQ4', 'avatar_url': 'https://avatars.githubusercontent.com/u/65625348?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/yli7-bloomberg', 'html_url': 'https://github.com/yli7-bloomberg', 'followers_url': 'https://api.github.com/users/yli7-bloomberg/followers', 'following_url': 'https://api.github.com/users/yli7-bloomberg/following{/other_user}', 'gists_url': 'https://api.github.com/users/yli7-bloomberg/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/yli7-bloomberg/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/yli7-bloomberg/subscriptions', 'organizations_url': 'https://api.github.com/users/yli7-bloomberg/orgs', 'repos_url': 'https://api.github.com/users/yli7-bloomberg/repos', 'events_url': 'https://api.github.com/users/yli7-bloomberg/events{/privacy}', 'received_events_url': 'https://api.github.com/users/yli7-bloomberg/received_events', 'type': 'User', 'site_admin': False}
{'login': 'YashpalAhlawat', 'id': 18135348, 'node_id': 'MDQ6VXNlcjE4MTM1MzQ4', 'avatar_url': 'https://avatars.githubusercontent.com/u/18135348?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/YashpalAhlawat', 'html_url': 'https://github.com/YashpalAhlawat', 'followers_url': 'https://api.github.com/users/YashpalAhlawat/followers', 'following_url': 'https://api.github.com/users/YashpalAhlawat/following{/other_user}', 'gists_url': 'https://api.github.com/users/YashpalAhlawat/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/YashpalAhlawat/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/YashpalAhlawat/subscriptions', 'organizations_url': 'https://api.github.com/users/YashpalAhlawat/orgs', 'repos_url': 'https://api.github.com/users/YashpalAhlawat/repos', 'events_url': 'https://api.github.com/users/YashpalAhlawat/events{/privacy}', 'received_events_url': 'https://api.github.com/users/YashpalAhlawat/received_events', 'type': 'User', 'site_admin': False}
{'login': 'iridiium', 'id': 60609879, 'node_id': 'MDQ6VXNlcjYwNjA5ODc5', 'avatar_url': 'https://avatars.githubusercontent.com/u/60609879?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/iridiium', 'html_url': 'https://github.com/iridiium', 'followers_url': 'https://api.github.com/users/iridiium/followers', 'following_url': 'https://api.github.com/users/iridiium/following{/other_user}', 'gists_url': 'https://api.github.com/users/iridiium/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/iridiium/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/iridiium/subscriptions', 'organizations_url': 'https://api.github.com/users/iridiium/orgs', 'repos_url': 'https://api.github.com/users/iridiium/repos', 'events_url': 'https://api.github.com/users/iridiium/events{/privacy}', 'received_events_url': 'https://api.github.com/users/iridiium/received_events', 'type': 'User', 'site_admin': False}
{'login': 'jorisvandenbossche', 'id': 1020496, 'node_id': 'MDQ6VXNlcjEwMjA0OTY=', 'avatar_url': 'https://avatars.githubusercontent.com/u/1020496?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jorisvandenbossche', 'html_url': 'https://github.com/jorisvandenbossche', 'followers_url': 'https://api.github.com/users/jorisvandenbossche/followers', 'following_url': 'https://api.github.com/users/jorisvandenbossche/following{/other_user}', 'gists_url': 'https://api.github.com/users/jorisvandenbossche/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jorisvandenbossche/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jorisvandenbossche/subscriptions', 'organizations_url': 'https://api.github.com/users/jorisvandenbossche/orgs', 'repos_url': 'https://api.github.com/users/jorisvandenbossche/repos', 'events_url': 'https://api.github.com/users/jorisvandenbossche/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jorisvandenbossche/received_events', 'type': 'User', 'site_admin': False}
{'login': 'JustAnotherVeryNormalDeveloper', 'id': 165384388, 'node_id': 'U_kgDOCduQxA', 'avatar_url': 'https://avatars.githubusercontent.com/u/165384388?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/JustAnotherVeryNormalDeveloper', 'html_url': 'https://github.com/JustAnotherVeryNormalDeveloper', 'followers_url': 'https://api.github.com/users/JustAnotherVeryNormalDeveloper/followers', 'following_url': 'https://api.github.com/users/JustAnotherVeryNormalDeveloper/following{/other_user}', 'gists_url': 'https://api.github.com/users/JustAnotherVeryNormalDeveloper/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/JustAnotherVeryNormalDeveloper/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/JustAnotherVeryNormalDeveloper/subscriptions', 'organizations_url': 'https://api.github.com/users/JustAnotherVeryNormalDeveloper/orgs', 'repos_url': 'https://api.github.com/users/JustAnotherVeryNormalDeveloper/repos', 'events_url': 'https://api.github.com/users/JustAnotherVeryNormalDeveloper/events{/privacy}', 'received_events_url': 'https://api.github.com/users/JustAnotherVeryNormalDeveloper/received_events', 'type': 'User', 'site_admin': False}
{'login': 'sdementen', 'id': 1304950, 'node_id': 'MDQ6VXNlcjEzMDQ5NTA=', 'avatar_url': 'https://avatars.githubusercontent.com/u/1304950?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/sdementen', 'html_url': 'https://github.com/sdementen', 'followers_url': 'https://api.github.com/users/sdementen/followers', 'following_url': 'https://api.github.com/users/sdementen/following{/other_user}', 'gists_url': 'https://api.github.com/users/sdementen/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/sdementen/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/sdementen/subscriptions', 'organizations_url': 'https://api.github.com/users/sdementen/orgs', 'repos_url': 'https://api.github.com/users/sdementen/repos', 'events_url': 'https://api.github.com/users/sdementen/events{/privacy}', 'received_events_url': 'https://api.github.com/users/sdementen/received_events', 'type': 'User', 'site_admin': False}
{'login': 'domsmrz', 'id': 3247179, 'node_id': 'MDQ6VXNlcjMyNDcxNzk=', 'avatar_url': 'https://avatars.githubusercontent.com/u/3247179?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/domsmrz', 'html_url': 'https://github.com/domsmrz', 'followers_url': 'https://api.github.com/users/domsmrz/followers', 'following_url': 'https://api.github.com/users/domsmrz/following{/other_user}', 'gists_url': 'https://api.github.com/users/domsmrz/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/domsmrz/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/domsmrz/subscriptions', 'organizations_url': 'https://api.github.com/users/domsmrz/orgs', 'repos_url': 'https://api.github.com/users/domsmrz/repos', 'events_url': 'https://api.github.com/users/domsmrz/events{/privacy}', 'received_events_url': 'https://api.github.com/users/domsmrz/received_events', 'type': 'User', 'site_admin': False}

In [12]:
for i in range(len(df)):
    print(df[i]['user']['node_id'])

U_kgDOB5xixA
MDQ6VXNlcjUyNzkyOTk5
MDQ6VXNlcjgwNzg5Njg=
U_kgDOB2aEBg
MDQ6VXNlcjQ3OTYzMjE1
MDQ6VXNlcjE0MDc1OTIy
MDQ6VXNlcjQ1NTYyNDAy
U_kgDOByhD2w
MDQ6VXNlcjkxMTYwNDc1
MDQ6VXNlcjI1NDY1NDM=
MDQ6VXNlcjUyNzkyOTk5
MDQ6VXNlcjM5NTA0MjMz
MDQ6VXNlcjUyNzkyOTk5
MDQ6VXNlcjY1NjI1MzQ4
MDQ6VXNlcjE4MTM1MzQ4
MDQ6VXNlcjYwNjA5ODc5
MDQ6VXNlcjEwMjA0OTY=
U_kgDOCduQxA
MDQ6VXNlcjEzMDQ5NTA=
MDQ6VXNlcjMyNDcxNzk=
MDQ6VXNlcjM1NjEzNDg3
MDQ6VXNlcjM1NjEzNDg3
MDQ6VXNlcjM1NjEzNDg3
MDQ6VXNlcjM1NjEzNDg3
MDQ6VXNlcjM1NjEzNDg3
MDQ6VXNlcjM1NjEzNDg3
MDQ6VXNlcjEwMzQxNzQ3
MDQ6VXNlcjgwODk2NjU1
MDQ6VXNlcjMyNDcxNzk=
MDQ6VXNlcjgwNzg5Njg=

In [13]:
pd.DataFrame(df)

,url,repository_url,labels_url,comments_url,events_url,html_url,id,node_id,number,title,...,closed_at,author_association,active_lock_reason,draft,pull_request,body,reactions,timeline_url,performed_via_github_app,state_reason
0,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/58091,2216730815,PR_kwDOAA0YD85rPMrj,58091,"DOC: Changed ndim to 1, modified doc as sugges...",...,None,NONE,None,False,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #57088,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None,None
1,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/58090,2216715546,PR_kwDOAA0YD85rPJ1e,58090,CI: Remove deprecated methods from code_checks.sh,...,None,CONTRIBUTOR,None,False,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] xref #58065 \r\n- [ ] [Tests added and p...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None,None
2,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/58089,2216677095,PR_kwDOAA0YD85rPDMB,58089,DEPR: Series setitem/getitem treating ints as ...,...,None,MEMBER,None,False,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #xxxx (Replace xxxx with the GitH...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None,None
3,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/58088,2216668448,PR_kwDOAA0YD85rPBn7,58088,BUG: Let `melt` name multiple variable columns...,...,None,CONTRIBUTOR,None,False,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #58033\r\n- [x] [Tests added and ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None,None
4,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/58087,2216590838,PR_kwDOAA0YD85rOzGF,58087,BLD: Build wheels using numpy 2.0rc1,...,None,MEMBER,None,False,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #55519 (Replace xxxx with the Gi...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None,None
5,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/58086,2216550242,I_kwDOAA0YD86EHd9i,58086,BUG: beautifulsoup4 breaks pandas.read_html,...,None,CONTRIBUTOR,None,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None,None
6,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/58085,2216480869,PR_kwDOAA0YD85rOcSY,58085,ENH: Enable fillna(value=None),...,None,MEMBER,None,True,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #57723 (Replace xxxx with the Git...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None,None
7,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/58084,2216346242,PR_kwDOAA0YD85rOBlK,58084,Use mask to create result_mask that filters na...,...,None,CONTRIBUTOR,None,False,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #xxxx (Replace xxxx with the GitH...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None,None
8,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/58083,2216118389,PR_kwDOAA0YD85rNTlX,58083,CLN: move raising TypeError for `interpolate` ...,...,None,CONTRIBUTOR,None,True,{'url': 'https://api.github.com/repos/pandas-d...,xref #57820\r\n\r\nmoved raising `TypeError` f...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None,None
9,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/58082,2216062901,PR_kwDOAA0YD85rNIGP,58082,Improve MultiIndex label rename checks,...,None,NONE,None,False,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #55169 \r\n- [x] [Tests added and...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None,None
10,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/58081,2216037782,PR_kwDOAA0YD85rNC0I,58081,ENH: Implement round dunder methods for Timest...,...,None,CONTRIBUTOR,None,False,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #58071\r\n- [ ] [Tests added and ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None,None
11,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/58080,2216022704,PR_kwDOAA0YD85rM_o_,58080,Backport PR #58075 on branch 2.2.x (DOC: whats...,...,None,CONTRIBUTOR,None,False,{'url': 'https://api.github.com/repos/pandas-d...,Backport PR #58075: DOC: whatsnew note for #57553,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None,None
12,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/58079,2215997850,PR_kwDOAA0YD85rM6Zi,58079,DOC: Update Categorical/CategoricalDtype metho...,...,None,CONTRIBUTOR,None,False,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #58064 \r\n- [ ] [Tests added and...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None,None
13,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/58078,2215950924,I_kwDOAA0YD86EFLpM,58078,BUG: Read hdfs:/// is broken since 2.1.0,...,None,NONE,None,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None,None
14,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/58076,2215864273,PR_kwDOAA0YD85rMeMR,58076,DOC: docstring fix for pandas.DataFrame.where ...,...,None,CONTRIBUTOR,None,False,{'url': 'https://api.github.com/repos/pandas-d...,- [x] xref #58065 (Replace xxxx with the GitHu...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None,None
15,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/58074,2215748323,PR_kwDOAA0YD85rMEi6,58074,DOC: fixed docstrings for pandas.DatetimeIndex...,...,None,NONE,None,False,{'url': 'https://api.github.com/repos/pandas-d...,- [x] [Tests added and passed](https://pandas....,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None,None
16,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/58072,2215498582,PR_kwDOAA0YD85rLODq,58072,Add `strict_na` keyword to the assert_.._equal...,...,None,MEMBER,None,True,{'url': 'https://api.github.com/repos/pandas-d...,Adding a `strict_na=False` option to our asser...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None,None
17,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/58071,2215159792,I_kwDOAA0YD86ECKfw,58071,"BUG: TypeError(""type Timedelta doesn't define ...",...,None,NONE,None,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None,None
18,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/58070,2215042082,I_kwDOAA0YD86EBtwi,58070,ENH: styler.to_excel to support excel notes as...,...,None,CONTRIBUTOR,None,NaN,NaN,### Feature Type\n\n- [X] Adding new functiona...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None,None
19,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/58069,2215041281,I_kwDOAA0YD86EBtkB,58069,BUG: Linux - Name of the returned series dropp...,...,None,NONE,None,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None,None
20,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/58068,2214815264,I_kwDOAA0YD86EA2Yg,58068,DOC: Enforce Numpy Docstring Validation | pand...,...,None,CONTRIBUTOR,None,NaN,NaN,[DOC: Enforce Numpy Docstring Validation (Pare...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None,None
21,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/58067,2214811314,I_kwDOAA0YD86EA1ay,58067,DOC: Enforce Numpy Docstring Validation | pand...,...,None,CONTRIBUTOR,None,NaN,NaN,[DOC: Enforce Numpy Docstring Validation (Pare...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None,None
22,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/58066,2214794201,I_kwDOAA0YD86EAxPZ,58066,DOC: Enforce Numpy Docstring Validation | pand...,...,None,CONTRIBUTOR,None,NaN,NaN,[DOC: Enforce Numpy Docstring Validation (Pare...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None,None
23,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/58065,2214790285,I_kwDOAA0YD86EAwSN,58065,DOC: Enforce Numpy Docstring Validation | pand...,...,None,CONTRIBUTOR,None,NaN,NaN,[DOC: Enforce Numpy Docstring Validation (Pare...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None,None
24,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/58064,2214788325,I_kwDOAA0YD86EAvzl,58064,DOC: Enforce Numpy Docstring Validation | pand...,...,None,CONTRIBUTOR,None,NaN,NaN,[DOC: Enforce Numpy Docstring Validation (Pare...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None,None
25,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/58063,2214763738,I_kwDOAA0YD86EApza,58063,DOC: Enforce Numpy Docstring Validation (Paren...,...,None,CONTRIBUTOR,None,NaN,NaN,Pandas has a script for validating docstrings:...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None,None
26,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/58062,2214674078,I_kwDOAA0YD86EAT6e,58062,BUG: Categorical columns using the PyArrow bac...,...,None,NONE,None,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None,None
27,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/58061,2214579740,I_kwDOAA0YD86D_84c,58061,QST: somthing weird in using groupby.rolling.a...,...,None,NONE,None,NaN,NaN,### Research\n\n- [X] I have searched the [[pa...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None,None
28,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/58057,2214305563,PR_kwDOAA0YD85rHLPE,58057,BUG: Allow using numpy in `DataFrame.eval` and...,...,None,NONE,None,False,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #58041\r\n- [x] [Tests added and ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None,None
29,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/58055,2214262085,I_kwDOAA0YD86D-vVF,58055,BUG: TestTableSchemaRepr::test_publishes raise...,...,None,MEMBER,None,NaN,NaN,```python\r\nTestTableSchemaRepr::test_publish...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None,None

In [14]:
df1=pd.DataFrame(df,columns=['user','timeline_url'])

In [15]:
df1.to_csv('json_info.csv')

In [16]:
df1.to_excel('json_excel.xlsx')

In [ ]:
#Solving the dataset

In [4]:
df=pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

URLError: <urlopen error [Errno 11001] getaddrinfo failed>

In [18]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [19]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [20]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [21]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [23]:
df.describe()#describe a numerical data

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
#no of children died and survived below 5 yrs
#in age col min age is means 0.420000 means 4 months 20days yr old
#25%-the percentage of people below that number.25% of people are equal to or below the age of 20 yr's old
#50%-the percentage of people below that number.50% of people are equal to or below the age of 28 yr's old
#75%-the percentage of people below that number.75% of people are equal to or below the age of 38 yr's old
#max:-the oldest person was died in that incident is 80 yr's old

In [24]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [25]:
df[['PassengerId', 'Survived', 'Pclass']]

     PassengerId  Survived  Pclass
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

[891 rows x 3 columns]

In [26]:
df.dtypes=='object'

PassengerId    False
Survived       False
Pclass         False
Name            True
Sex             True
Age            False
SibSp          False
Parch          False
Ticket          True
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [27]:
type(df.dtypes=='object')

pandas.core.series.Series

In [28]:
[df.dtypes=='object'].index

In [29]:
df.dtypes[df.dtypes=='object'].index

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [30]:
df[df.dtypes[df.dtypes=='object'].index]

,Name,Sex,Ticket,Cabin,Embarked
0,"Braund, Mr. Owen Harris",male,A/5 21171,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,PC 17599,C85,C
2,"Heikkinen, Miss. Laina",female,STON/O2. 3101282,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,113803,C123,S
4,"Allen, Mr. William Henry",male,373450,NaN,S
...,...,...,...,...,...
886,"Montvila, Rev. Juozas",male,211536,NaN,S
887,"Graham, Miss. Margaret Edith",female,112053,B42,S
888,"Johnston, Miss. Catherine Helen ""Carrie""",female,W./C. 6607,NaN,S
889,"Behr, Mr. Karl Howell",male,111369,C148,C
890,"Dooley, Mr. Patrick",male,370376,NaN,Q

In [31]:
df[df.columns[df.dtypes=='object']]#alternative way

,Name,Sex,Ticket,Cabin,Embarked
0,"Braund, Mr. Owen Harris",male,A/5 21171,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,PC 17599,C85,C
2,"Heikkinen, Miss. Laina",female,STON/O2. 3101282,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,113803,C123,S
4,"Allen, Mr. William Henry",male,373450,NaN,S
...,...,...,...,...,...
886,"Montvila, Rev. Juozas",male,211536,NaN,S
887,"Graham, Miss. Margaret Edith",female,112053,B42,S
888,"Johnston, Miss. Catherine Helen ""Carrie""",female,W./C. 6607,NaN,S
889,"Behr, Mr. Karl Howell",male,111369,C148,C
890,"Dooley, Mr. Patrick",male,370376,NaN,Q

In [32]:
df[df.columns[df.dtypes!='object']]

     PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare
0              1         0       3  22.0      1      0   7.2500
1              2         1       1  38.0      1      0  71.2833
2              3         1       3  26.0      0      0   7.9250
3              4         1       1  35.0      1      0  53.1000
4              5         0       3  35.0      0      0   8.0500
..           ...       ...     ...   ...    ...    ...      ...
886          887         0       2  27.0      0      0  13.0000
887          888         1       1  19.0      0      0  30.0000
888          889         0       3   NaN      1      2  23.4500
889          890         1       1  26.0      0      0  30.0000
890          891         0       3  32.0      0      0   7.7500

[891 rows x 7 columns]

In [33]:
df[df.dtypes[df.dtypes!='object'].index]

     PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare
0              1         0       3  22.0      1      0   7.2500
1              2         1       1  38.0      1      0  71.2833
2              3         1       3  26.0      0      0   7.9250
3              4         1       1  35.0      1      0  53.1000
4              5         0       3  35.0      0      0   8.0500
..           ...       ...     ...   ...    ...    ...      ...
886          887         0       2  27.0      0      0  13.0000
887          888         1       1  19.0      0      0  30.0000
888          889         0       3   NaN      1      2  23.4500
889          890         1       1  26.0      0      0  30.0000
890          891         0       3  32.0      0      0   7.7500

[891 rows x 7 columns]

In [34]:
df[df.dtypes[df.dtypes!='object'].index].describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [35]:
df[df.dtypes[df.dtypes=='object'].index].describe()

                           Name   Sex  Ticket    Cabin Embarked
count                       891   891     891      204      889
unique                      891     2     681      147        3
top     Braund, Mr. Owen Harris  male  347082  B96 B98        S
freq                          1   577       7        4      644

In [ ]:
#might have null val,it means in 1 cabin multiple passangers

In [36]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [37]:
df.describe(include='object')

                           Name   Sex  Ticket    Cabin Embarked
count                       891   891     891      204      889
unique                      891     2     681      147        3
top     Braund, Mr. Owen Harris  male  347082  B96 B98        S
freq                          1   577       7        4      644

In [38]:
df.describe(include='all')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891.000000,891.000000,891.000000,891,891,714.000000,891.000000,891.000000,891,891.000000,204,889
unique,NaN,NaN,NaN,891,2,NaN,NaN,NaN,681,NaN,147,3
top,NaN,NaN,NaN,"Braund, Mr. Owen Harris",male,NaN,NaN,NaN,347082,NaN,B96 B98,S
freq,NaN,NaN,NaN,1,577,NaN,NaN,NaN,7,NaN,4,644
mean,446.000000,0.383838,2.308642,NaN,NaN,29.699118,0.523008,0.381594,NaN,32.204208,NaN,NaN
std,257.353842,0.486592,0.836071,NaN,NaN,14.526497,1.102743,0.806057,NaN,49.693429,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN,NaN
25%,223.500000,0.000000,2.000000,NaN,NaN,20.125000,0.000000,0.000000,NaN,7.910400,NaN,NaN
50%,446.000000,0.000000,3.000000,NaN,NaN,28.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN
75%,668.500000,1.000000,3.000000,NaN,NaN,38.000000,1.000000,0.000000,NaN,31.000000,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN,NaN

In [39]:
df.astype('object').describe()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891,891,891,891,891,714.0,891,891,891,891.00,204,889
unique,891,2,3,891,2,88.0,7,7,681,248.00,147,3
top,1,0,3,"Braund, Mr. Owen Harris",male,24.0,0,0,347082,8.05,B96 B98,S
freq,1,549,491,1,577,30.0,608,678,7,43.00,4,644

In [ ]:
========================================================================================================

In [40]:
import pandas as pd
import numpy as np

In [41]:
df=pd.read_csv('titanic.csv')

In [42]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [43]:
df.astype('object').describe()#all col's converted into object

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891,891,891,891,891,714.0,891,891,891,891.00,204,889
unique,891,2,3,891,2,88.0,7,7,681,248.00,147,3
top,1,0,3,"Braund, Mr. Owen Harris",male,24.0,0,0,347082,8.05,B96 B98,S
freq,1,549,491,1,577,30.0,608,678,7,43.00,4,644

In [44]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [45]:
df[1:10]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [46]:
df[10:100]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,0,3,"Shorney, Mr. Charles Joseph",male,NaN,0,0,374910,8.0500,NaN,S
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
97,98,1,1,"Greenfield, Mr. William Bertram",male,23.0,0,1,PC 17759,63.3583,D10 D12,C
98,99,1,2,"Doling, Mrs. John T (Ada Julia Bone)",female,34.0,0,1,231919,23.0000,NaN,S
99,100,0,2,"Kantor, Mr. Sinai",male,34.0,1,0,244367,26.0000,NaN,S

In [47]:
df[10:100:2]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.00,1,1,PP 9549,16.7000,G6,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.00,0,0,A/5. 2151,8.0500,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.00,0,0,350406,7.8542,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.00,4,1,382652,29.1250,NaN,Q
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.00,1,0,345763,18.0000,NaN,S
20,21,0,2,"Fynney, Mr. Joseph J",male,35.00,0,0,239865,26.0000,NaN,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.00,0,0,330923,8.0292,NaN,Q
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.00,3,1,349909,21.0750,NaN,S
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
30,31,0,1,"Uruchurtu, Don. Manuel E",male,40.00,0,0,PC 17601,27.7208,NaN,C
32,33,1,3,"Glynn, Miss. Mary Agatha",female,NaN,0,0,335677,7.7500,NaN,Q
34,35,0,1,"Meyer, Mr. Edgar Joseph",male,28.00,1,0,PC 17604,82.1708,NaN,C
36,37,1,3,"Mamee, Mr. Hanna",male,NaN,0,0,2677,7.2292,NaN,C
38,39,0,3,"Vander Planke, Miss. Augusta Maria",female,18.00,2,0,345764,18.0000,NaN,S
40,41,0,3,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",female,40.00,1,0,7546,9.4750,NaN,S
42,43,0,3,"Kraeff, Mr. Theodor",male,NaN,0,0,349253,7.8958,NaN,C
44,45,1,3,"Devaney, Miss. Margaret Delia",female,19.00,0,0,330958,7.8792,NaN,Q
46,47,0,3,"Lennon, Mr. Denis",male,NaN,1,0,370371,15.5000,NaN,Q
48,49,0,3,"Samaan, Mr. Youssef",male,NaN,2,0,2662,21.6792,NaN,C
50,51,0,3,"Panula, Master. Juha Niilo",male,7.00,4,1,3101295,39.6875,NaN,S
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.00,1,0,PC 17572,76.7292,D33,C
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.00,0,1,113509,61.9792,B30,C
56,57,1,2,"Rugg, Miss. Emily",female,21.00,0,0,C.A. 31026,10.5000,NaN,S
58,59,1,2,"West, Miss. Constance Mirium",female,5.00,1,2,C.A. 34651,27.7500,NaN,S
60,61,0,3,"Sirayanian, Mr. Orsen",male,22.00,0,0,2669,7.2292,NaN,C
62,63,0,1,"Harris, Mr. Henry Birkhardt",male,45.00,1,0,36973,83.4750,C83,S
64,65,0,1,"Stewart, Mr. Albert A",male,NaN,0,0,PC 17605,27.7208,NaN,C
66,67,1,2,"Nye, Mrs. (Elizabeth Ramell)",female,29.00,0,0,C.A. 29395,10.5000,F33,S
68,69,1,3,"Andersson, Miss. Erna Alexandra",female,17.00,4,2,3101281,7.9250,NaN,S
70,71,0,2,"Jenkin, Mr. Stephen Curnow",male,32.00,0,0,C.A. 33111,10.5000,NaN,S
72,73,0,2,"Hood, Mr. Ambrose Jr",male,21.00,0,0,S.O.C. 14879,73.5000,NaN,S
74,75,1,3,"Bing, Mr. Lee",male,32.00,0,0,1601,56.4958,NaN,S
76,77,0,3,"Staneff, Mr. Ivan",male,NaN,0,0,349208,7.8958,NaN,S
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S
80,81,0,3,"Waelens, Mr. Achille",male,22.00,0,0,345767,9.0000,NaN,S
82,83,1,3,"McDermott, Miss. Brigdet Delia",female,NaN,0,0,330932,7.7875,NaN,Q
84,85,1,2,"Ilett, Miss. Bertha",female,17.00,0,0,SO/C 14885,10.5000,NaN,S
86,87,0,3,"Ford, Mr. William Neal",male,16.00,1,3,W./C. 6608,34.3750,NaN,S
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.00,3,2,19950,263.0000,C23 C25 C27,S
90,91,0,3,"Christmann, Mr. Emil",male,29.00,0,0,343276,8.0500,NaN,S
92,93,0,1,"Chaffee, Mr. Herbert Fuller",male,46.00,1,0,W.E.P. 5734,61.1750,E31,S
94,95,0,3,"Coxon, Mr. Daniel",male,59.00,0,0,364500,7.2500,NaN,S
96,97,0,1,"Goldschmidt, Mr. George B",male,71.00,0,0,PC 17754,34.6542,A5,C
98,99,1,2,"Doling, Mrs. John T (Ada Julia Bone)",female,34.00,0,1,231919,23.0000,NaN,S

In [48]:
df['new_col']="Lalit"

In [49]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Lalit
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Lalit
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Lalit
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Lalit
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Lalit
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Lalit
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Lalit
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,Lalit
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Lalit
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Lalit

In [50]:
df['family'] = df['SibSp'] + df['Parch']

In [51]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col,family
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Lalit,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Lalit,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Lalit,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Lalit,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Lalit,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Lalit,0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Lalit,0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,Lalit,3
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Lalit,0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Lalit,0

In [52]:
df['Pclass']

0      3
1      1
2      3
3      1
4      3
      ..
886    2
887    1
888    3
889    1
890    3
Name: Pclass, Length: 891, dtype: int64

In [53]:
pd.Categorical(df['Pclass'])

[3, 1, 3, 1, 3, ..., 2, 1, 3, 1, 3]
Length: 891
Categories (3, int64): [1, 2, 3]

In [54]:
pd.Categorical(df['Cabin'])

[NaN, 'C85', NaN, 'C123', NaN, ..., NaN, 'B42', NaN, 'C148', NaN]
Length: 891
Categories (147, object): ['A10', 'A14', 'A16', 'A19', ..., 'F38', 'F4', 'G6', 'T']

In [55]:
df['Cabin'].unique()

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4',
       'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19',
       'B49', 'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54',
       'B57 B59 B63 B66', 'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40',
       'T', 'C128', 'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44',
       'A34', 'C104', 'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14',
       'B37', 'C30', 'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38',
       'B39', 'B22', 'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68',
       'B41', 'A20', 'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48',
       'E58', 'C126', 'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63',
       'C62 C64', 'E24', 'C90', 'C45', 'E8', 'B101', 'D45', 'C46', 'D30',
       'E121', 'D11', 'E77', 'F38', 'B3', 'D6', 'B82 B84', 'D17', 'A36',
       'B102', 'B69', 'E49', 'C47', 'D28', 'E17', 'A24', 'C50', 'B42',
       'C148'], dtype=object)

In [56]:
df['Cabin'].nunique()

147

In [57]:
df['Cabin'].value_counts()

Cabin
B96 B98        4
G6             4
C23 C25 C27    4
C22 C26        3
F33            3
              ..
E34            1
C7             1
C54            1
E36            1
C148           1
Name: count, Length: 147, dtype: int64

In [ ]:
#Q1.How many passangers are less than 5 yrs old

In [58]:
df['Age'] < 5

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [ ]:
df[df['Age']<5]

In [59]:
len(df[df['Age']<5])

40

In [ ]:
#No.of passengers > 18
df[df['Age']>18]

In [ ]:
len(df[df['Age']>18])

In [63]:
#how many passengers are less than 18 yrs old
len(df) - len(df[df['Age']>=18])

290

In [61]:
len(df[df['Age'] <= 18])

139

In [64]:
#Q.How many passengers have paid less than avg fare
#calculate avg fare
df['Fare'].mean()

32.204207968574636

In [65]:
df.describe().mean()

PassengerId    478.044230
Survived       111.733804
Pclass         113.268089
Age            115.596327
SibSp          112.703219
Parch          112.273456
Fare           192.323930
family         113.064758
dtype: float64

In [66]:
df[df['Fare']<df['Fare'].mean()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col,family
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Lalit,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Lalit,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Lalit,0
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,Lalit,0
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,Lalit,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Lalit,0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Lalit,0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,Lalit,3
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Lalit,0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Lalit,0

In [67]:
len(df[df['Fare']<df['Fare'].mean()])

680

In [68]:
df[df['Fare'] < 32]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col,family
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Lalit,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Lalit,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Lalit,0
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,Lalit,0
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,Lalit,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Lalit,0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Lalit,0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,Lalit,3
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Lalit,0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Lalit,0

In [69]:
df[df['Fare']>df['Fare'].mean()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col,family
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Lalit,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Lalit,1
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,Lalit,0
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S,Lalit,0
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S,Lalit,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,1,1,36928,164.8667,NaN,S,Lalit,2
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S,Lalit,10
867,868,0,1,"Roebling, Mr. Washington Augustus II",male,31.0,0,0,PC 17590,50.4958,A24,S,Lalit,0
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S,Lalit,2
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C,Lalit,1

In [ ]:
len(df[df['Fare']>df['Fare'].mean()])

In [ ]:
#Q.How Many Passengers paid 0 fare
df[df['Fare'] == 0]

In [ ]:
len(df[df['Fare'] == 0])

In [ ]:
df[df['Fare'] == 0].Name

In [70]:
list(df[df['Fare'] == 0].Name)

['Leonard, Mr. Lionel',
 'Harrison, Mr. William',
 'Tornquist, Mr. William Henry',
 'Parkes, Mr. Francis "Frank"',
 'Johnson, Mr. William Cahoone Jr',
 'Cunningham, Mr. Alfred Fleming',
 'Campbell, Mr. William',
 'Frost, Mr. Anthony Wood "Archie"',
 'Johnson, Mr. Alfred',
 'Parr, Mr. William Henry Marsh',
 'Watson, Mr. Ennis Hastings',
 'Knight, Mr. Robert J',
 'Andrews, Mr. Thomas Jr',
 'Fry, Mr. Richard',
 'Reuchlin, Jonkheer. John George']

In [ ]:
#How Many Passengers are male and female

len(df[df['Sex']=='male'])

In [ ]:
len(df[df['Sex']=='female'])

In [71]:
df['Sex'].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [72]:
df['Sex'].value_counts(normalize=True)

Sex
male      0.647587
female    0.352413
Name: proportion, dtype: float64

In [ ]:
df['Sex'].value_counts(normalize=True).male

In [ ]:
df['Sex'].value_counts(normalize=True).female

In [ ]:
#Q.How many passengers of class 1

df[df['Pclass']==1]

In [ ]:
df[df['Survived']==1]

In [73]:
len(df[df['Survived']==1])

342

In [74]:
df['Survived'].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [75]:
df['Survived'].value_counts(normalize=True)

Survived
0    0.616162
1    0.383838
Name: proportion, dtype: float64

In [ ]:
#How Many femails paid more than avg fare
df['Fare'].mean()

In [ ]:
df[(df['Sex']=='female') & (df['Fare'] > df['Fare'].mean())]

In [ ]:
#Qn.How Many Passenger are Male or Greter than avg fare
df[(df['Sex']=='male') | (df['Fare'] > df['Fare'].mean())]

In [77]:
#How Many Pass are Male and greater than avg  fair
df[(df['Sex']=='male') & (df['Fare'] > df['Fare'].mean())]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col,family
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,Lalit,0
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S,Lalit,0
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S,Lalit,5
34,35,0,1,"Meyer, Mr. Edgar Joseph",male,28.0,1,0,PC 17604,82.1708,NaN,C,Lalit,1
35,36,0,1,"Holverson, Mr. Alexander Oskar",male,42.0,1,0,113789,52.0000,NaN,S,Lalit,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
827,828,1,2,"Mallet, Master. Andre",male,1.0,0,2,S.C./PARIS 2079,37.0042,NaN,C,Lalit,2
838,839,1,3,"Chip, Mr. Chang",male,32.0,0,0,1601,56.4958,NaN,S,Lalit,0
846,847,0,3,"Sage, Mr. Douglas Bullen",male,NaN,8,2,CA. 2343,69.5500,NaN,S,Lalit,10
848,849,0,2,"Harper, Rev. John",male,28.0,0,1,248727,33.0000,NaN,S,Lalit,1
867,868,0,1,"Roebling, Mr. Washington Augustus II",male,31.0,0,0,PC 17590,50.4958,A24,S,Lalit,0

In [76]:
np.mean(df['Fare'])

32.204207968574636

In [ ]:
df['Fare'].mean()

In [ ]:
max(df['Fare'])

In [ ]:
min(df['Fare'])

In [ ]:
#who are the passengers who paid maximum fare
df[df['Fare']==max(df['Fare'])]['Name']

In [ ]:
"""Qn.How Many Passengers have parch greater than 3
   Qn.How Many Passengers who survived paid the maximum fare
   Qn.How many Passengers who didnt survived was from class 1
   Qn.How many Passengers are having children (<5 years old)
"""

In [1]:
#Access df rows
df[0:100:2]

NameError: name 'df' is not defined

In [ ]:
#implicit index(internal/interger index) and explicit index(that were defined by us)/named indexing/name

In [8]:
df = pd.read_csv("C:\\Users\\boras\\Downloads\\titanic.csv")

In [9]:
df.iloc[0:2] # start from 0 go to 1 excluding 2/iloc is integer index/inplicit index
#istand for interger indexing

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [10]:
df.loc[0:2] # give me the rows whose name is 0,1,2 #location treat as name,loc is named index/explicit index

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [ ]:
#loc will go with named index, iloc will go with inbuilt index

In [12]:
df.iloc[0:2,['Name','Sex','Age']]#it throws thee error

In [13]:
df.loc[0:2,['Name','Sex','Age']]

                                                Name     Sex   Age
0                            Braund, Mr. Owen Harris    male  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                             Heikkinen, Miss. Laina  female  26.0

In [ ]:
df

In [14]:
df.iloc[0:2,3:6]

                                                Name     Sex   Age
0                            Braund, Mr. Owen Harris    male  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0

In [15]:
df.iloc[0:2,[0,1,2,3,4,5]]

,PassengerId,Survived,Pclass,Name,Sex,Age
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0

In [16]:
df['Name'][2:14]

2                                Heikkinen, Miss. Laina
3          Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                              Allen, Mr. William Henry
5                                      Moran, Mr. James
6                               McCarthy, Mr. Timothy J
7                        Palsson, Master. Gosta Leonard
8     Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9                   Nasser, Mrs. Nicholas (Adele Achem)
10                      Sandstrom, Miss. Marguerite Rut
11                             Bonnell, Miss. Elizabeth
12                       Saundercock, Mr. William Henry
13                          Andersson, Mr. Anders Johan
Name: Name, dtype: object

In [18]:
len(df['Name'][2:14])

12

In [19]:
list(df['Name'][2:5])

['Heikkinen, Miss. Laina',
 'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
 'Allen, Mr. William Henry']

In [23]:
s=pd.Series(list(df['Name'][2:5]),index=['a','b','c'])

In [ ]:
s

In [ ]:
type(s)

In [20]:
s1=pd.Series(list(df['Name'][5:8]),index=['a','b','c'])

In [21]:
s1

a                  Moran, Mr. James
b           McCarthy, Mr. Timothy J
c    Palsson, Master. Gosta Leonard
dtype: object

In [24]:
s+s1

a               Heikkinen, Miss. LainaMoran, Mr. James
b    Futrelle, Mrs. Jacques Heath (Lily May Peel)Mc...
c    Allen, Mr. William HenryPalsson, Master. Gosta...
dtype: object

In [25]:
s=pd.Series(list(df['Name'][2:5]),index=['a','b','c'])

In [26]:
s1=pd.Series(list(df['Name'][5:8]))

In [27]:
s+s1#series or dataframe doesn't work with +

a    NaN
b    NaN
c    NaN
0    NaN
1    NaN
2    NaN
dtype: object

In [28]:
pd.concat([s,s1])

a                          Heikkinen, Miss. Laina
b    Futrelle, Mrs. Jacques Heath (Lily May Peel)
c                        Allen, Mr. William Henry
0                                Moran, Mr. James
1                         McCarthy, Mr. Timothy J
2                  Palsson, Master. Gosta Leonard
dtype: object

In [29]:
#s.append(s1)
pd.concat([s,s1])

a                          Heikkinen, Miss. Laina
b    Futrelle, Mrs. Jacques Heath (Lily May Peel)
c                        Allen, Mr. William Henry
0                                Moran, Mr. James
1                         McCarthy, Mr. Timothy J
2                  Palsson, Master. Gosta Leonard
dtype: object

In [ ]:
#new

In [ ]:
s=pd.Series(list(df['Name'][2:5]),index=['a','b','c'])

In [ ]:
s1=pd.Series(list(df['Name'][5:8]),index=['a','b','c'])

In [ ]:
s+s1

In [30]:
pd.concat([s,s1])

a                          Heikkinen, Miss. Laina
b    Futrelle, Mrs. Jacques Heath (Lily May Peel)
c                        Allen, Mr. William Henry
0                                Moran, Mr. James
1                         McCarthy, Mr. Timothy J
2                  Palsson, Master. Gosta Leonard
dtype: object

In [31]:
df.drop('PassengerId')#row->axis=0 , col->axis->1

KeyError: "['PassengerId'] not found in axis"

In [ ]:
df.columns

In [ ]:
df.drop('Unnamed: 0',axis=1)

In [ ]:
df

In [ ]:
df.drop('Unnamed: 0',axis=1,inplace=True)

In [ ]:
df

In [ ]:
df.drop(1,inplace=True)#not can be rollback,consider row as a named index

In [ ]:
df

In [ ]:
df

In [ ]:
df

In [ ]:
#make a name col as index

In [32]:
df.set_index('Name',inplace=True)#time series data->you will making date time col as index

In [33]:
df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,,
"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S
"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
"Montvila, Rev. Juozas",887,0,2,male,27.0,0,0,211536,13.0000,NaN,S
"Graham, Miss. Margaret Edith",888,1,1,female,19.0,0,0,112053,30.0000,B42,S
"Johnston, Miss. Catherine Helen ""Carrie""",889,0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
"Behr, Mr. Karl Howell",890,1,1,male,26.0,0,0,111369,30.0000,C148,C
"Dooley, Mr. Patrick",891,0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [34]:
df.loc['Allen, Mr. William Henry']

PassengerId         5
Survived            0
Pclass              3
Sex              male
Age              35.0
SibSp               0
Parch               0
Ticket         373450
Fare             8.05
Cabin             NaN
Embarked            S
Name: Allen, Mr. William Henry, dtype: object

In [ ]:
df.iloc[1]#at background store the index

In [ ]:
df.head()

In [ ]:
df.reset_index(inplace=True)#it get back again inplicit index again

In [ ]:
df

In [ ]:
#Make a data frame using dict
d = {"key1":[1,2,3,4,9,3],
    "key2":[11,22,33,44,55,66],
    "key3":['a','b','c','d','e','f']}

In [ ]:
d

In [ ]:
pd.DataFrame(d)

In [ ]:
d1= {"key1":(1,2,3,4,9,3),
    "key2":(11,22,33,44,55,66),
    "key3":('a','b','c','d','e','f')}

In [ ]:
d1

In [ ]:
pd.DataFrame(d1)

In [ ]:
df1 = pd.read_csv("taxonomy.csv.xls")

In [ ]:
df1

In [ ]:
df1.shape

In [ ]:
df1.ndim

In [ ]:
df1.info()

In [ ]:
df1.isnull()

In [ ]:
df1.isnull().sum()

In [ ]:
df1

In [ ]:
df1.dropna()

In [ ]:
df1

In [ ]:
df1.dropna(inplace=True)#drop row wise

In [ ]:
df1

In [ ]:
df2=pd.read_csv('taxonomy.csv.xls')

In [ ]:
df2.dropna(axis=1)#col have null value it is droped

In [ ]:
df2

In [ ]:
#when a value are drop will col wise then value are droped by rows also

In [ ]:
df2.dropna(axis=1)

In [ ]:
df2[['name']].dropna(axis=1)#for on col

In [ ]:
df2

In [ ]:
df2.fillna("Missing Value_Here",inplace=True)

In [ ]:
df2

In [ ]:
df

In [ ]:
#Qn.What is the avg fare paid by people who survived?

In [24]:
#using group by
df.groupby('Survived').mean(numeric_only=True)

,Unnamed: 0,PassengerId,Pclass,Age,SibSp,Parch,Fare
Survived,,,,,,,
0,446.016393,447.016393,2.531876,30.626179,0.553734,0.329690,22.117887
1,443.368421,444.368421,1.950292,28.343690,0.473684,0.464912,48.395408

In [13]:
import pandas as pd
df =pd.read_csv("titanic.csv")

In [14]:
df

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [15]:
df.groupby('Survived').describe()

         Unnamed: 0                                                            \
              count        mean         std  min     25%    50%    75%    max
Survived
0             549.0  446.016393  260.640469  0.0  210.00  454.0  674.0  890.0
1             342.0  443.368421  252.358840  1.0  249.75  438.5  650.5  889.0

         PassengerId              ... Parch        Fare                        \
               count        mean  ...   75%  max  count       mean        std
Survived                          ...
0              549.0  447.016393  ...   0.0  6.0  549.0  22.117887  31.388207
1              342.0  444.368421  ...   1.0  5.0  342.0  48.395408  66.596998


          min      25%   50%   75%       max
Survived
0         0.0   7.8542  10.5  26.0  263.0000
1         0.0  12.4750  26.0  57.0  512.3292

[2 rows x 56 columns]

In [28]:
import numpy as np
df.groupby('Survived').aggregate([min,max,'median','count',np.std,'var'])

TypeError: could not convert string to float: 'Braund, Mr. Owen Harris'

In [ ]:
#groupby with two cols
#Q.Avg People who servived for each sex(male or female) , pclass

In [22]:
df.groupby(['Sex','Pclass'])['Survived'].sum()

Sex     Pclass
female  1         91
        2         70
        3         72
male    1         45
        2         17
        3         47
Name: Survived, dtype: int64

In [ ]:
#female who servived having Passenger class 1 is 91, Passenger Class 2 70 , Passenger class 72